### ISSUE TITLE
Error downloading 1.19 jar

### ISSUE THREAD

**Issue by Eejit43** [PrismarineJS/node-minecraft-wrap#67]
When downloading the `1.19` jar file I'm running into the following error:

```text
Error: download failed : wrong or partial file downloaded https://piston-meta.mojang.com/v1/packages/b03af5eb291163f7acc042d1553f2d212b220ecc/1.19.json <path>/minecraft-jar-extractor/versions/1.19/1.19.json
    at <path>/minecraft-jar-extractor/node_modules/minecraft-wrap/lib/etag_download.js:39:30
    at<path>/minecraft-jar-extractor/node_modules/minecraft-wrap/lib/etag_download.js:58:5
    at Hash.<anonymous> (<path>/minecraft-jar-extractor/node_modules/md5-file/index.js:38:5)
    at Object.onceWrapper (node:events:641:28)
    at Hash.emit (node:events:527:28)
    at emitReadable_ (node:internal/streams/readable:601:12)
    at onEofChunk (node:internal/streams/readable:579:5)
    at readableAddChunk (node:internal/streams/readable:275:5)
    at Hash.Readable.push (node:internal/streams/readable:234:10)
    at node:internal/streams/transform:126:12
```

Appears to be an issue with an updated `etag` headers that differs from the parsed `md5` sum

**Comment by Eejit43** [comment]
This also could be related to a recent change where the url of the version manifest used by the launcher changed from `launcher-meta.mojang.com` to `piston-meta.mojang.com`
